version: '3.7'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # migration:
  #   build: .
  #   env_file: .env
  #   command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; flask db migrate && flask db upgrade'
  #   restart: always
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db

  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; flask run --host=127.0.0.1 --port=5000'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    depends_on:
      - db
      - migration
volumes:
    pgdata: