version: '3.7'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - pgdata:/var/lib/mysqldata/data
    restart: always

  migration:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; flask db migrate && flask db upgrade'
    volumes:
      - .:/code
    depends_on:
      - db
    restart: always

  web:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; flask run --host=0.0.0.0 --port=5000'
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    depends_on:
      - db
      - migration
volumes:
    pgdata: