"""empty message

Revision ID: 207f1f70edbb
Revises: 
Create Date: 2022-07-12 08:12:08.553810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207f1f70edbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pessoa',
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dataNascimento', sa.Date(), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('idPessoa'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('Conta',
    sa.Column('idConta', sa.Integer(), nullable=False),
    sa.Column('idPessoa', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('limiteSaqueDiario', sa.Float(), nullable=True),
    sa.Column('flagAtivo', sa.Boolean(), nullable=True),
    sa.Column('tipoConta', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idPessoa'], ['Pessoa.idPessoa'], ),
    sa.PrimaryKeyConstraint('idConta'),
    sa.UniqueConstraint('idPessoa')
    )
    op.create_table('Transacao',
    sa.Column('idTransacao', sa.Integer(), nullable=False),
    sa.Column('idConta', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(precision=2), nullable=False),
    sa.Column('dataTransacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idConta'], ['Conta.idConta'], ),
    sa.PrimaryKeyConstraint('idTransacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transacao')
    op.drop_table('Conta')
    op.drop_table('Pessoa')
    # ### end Alembic commands ###
